newott/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieshd.urls')),
    path('',include('dashboard.urls')),
    path('',include('publisher.urls')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieshd/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime
from datetime import timedelta
from datetime import datetime as dt
today= datetime.date.today()


class customer(models.Model):
    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='static/images', null=True, blank=True)
    mobile = models.CharField(max_length=20, null=False)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES,
                              default='Male')
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class publisher(models.Model):
    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='static/images', null=True, blank=True)
    certificate = models.ImageField(upload_to='static/images', null=True, blank=True)
    mobile = models.CharField(max_length=20, null=False)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES,
                              default='Male')
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.first_name


class add_categories(models.Model):
    category_choice = [('Movie', 'Movie'), ('Show', 'Show'), ('Webseries', 'Webseries'), ('Kids', 'Kids')]
    language_choice = [('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('Tamil', 'Tamil'),
                       ('Malayalam', 'Malayalam'), ('Kannada', 'Kannada'), ('English', 'English')]
    geners_choice = [('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'),
                     ('Horror', 'Horror'), ('Thirller', 'Thirller'), ('Drama', 'Drama'),
                     ('Romance', 'Romance'), ('Sci Fi', 'Sci Fi')]
    uploader_name=models.CharField(max_length=500)
    category=models.CharField(max_length=500,choices=category_choice)
    title=models.CharField(max_length=500)
    discription = models.CharField(max_length=10000, null=True, blank=True)
    image = models.ImageField(upload_to="static/images", null=True, blank=True)
    language=models.CharField(max_length=500,choices=language_choice)
    geners=models.CharField(max_length=500,choices=geners_choice)
    screen_shot = models.ImageField(upload_to='static/images', null=True, blank=True)
    movie_length = models.CharField(max_length=50, null=True, blank=True)
    movie_director = models.CharField(max_length=200, null=True, blank=True)
    actor_name = models.CharField(max_length=1000, null=True, blank=True)
    movie_link = models.CharField(max_length=10000, null=True, blank=True)
    status=models.BooleanField(default=0)

    def __str__(self):
        return self.title



#### User Payment History
# class PayHistory(models.Model):
#     user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
#     amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
#     order_id = models.CharField(max_length=200)
#     date = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return self.user.username

#### Membership
class Membership(models.Model):
    MEMBERSHIP_CHOICES = (
        ('Basic', 'Basic'),
        ('Silver', 'Silver'),
        ('Gold', 'Gold'),
        ('Premium', 'Premium'),
    )
    PERIOD_DURATION = (
        ('Days', 'Days'),
        ('Week', 'Week'),
        ('Months', 'Months'),
    )
    slug = models.SlugField(null=True, blank=True)
    membership_type = models.CharField(choices=MEMBERSHIP_CHOICES, default='Free', max_length=30)
    duration = models.PositiveIntegerField(default=7)
    duration_period = models.CharField(max_length=100, default='Day', choices=PERIOD_DURATION)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
       return self.membership_type

#### User Membership
class UserMembership(models.Model):
    user = models.OneToOneField(User, related_name='user_membership', on_delete=models.CASCADE)
    membership = models.ForeignKey(Membership, related_name='user_membership', on_delete=models.SET_NULL, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    order_id = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
       return self.user.username

@receiver(post_save, sender=UserMembership)
def create_subscription(sender, instance, *args, **kwargs):
    if instance:
        Subscription.objects.create(user_membership=instance,
                                    expires_in=dt.now().date() + timedelta(days=instance.membership.duration))

#### User Subscription
class Subscription(models.Model):
    user_membership = models.ForeignKey(UserMembership, related_name='subscription', on_delete=models.CASCADE, default=None)
    expires_in = models.DateField(null=True, blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
      return self.user_membership.user.username

@receiver(post_save, sender=Subscription)
def update_acive(sender, instance, *args, **kwargs):
    if instance.expires_in < today:
        subscription=Subscription.objects.get(id=instance.id)
        subscription.delete()

templates/publisher1/index.html
{% extends 'publisher1/pub_base.html' %}
{% block content %}
    <!-- main content -->
    <main class="main">
        <div class="container-fluid">
            <div class="row row--grid">
                <!-- main title -->
                <div class="col-12">
                    <div class="main__title">
                        <h2>publisher</h2>

                        <a href="/padd" class="main__title-link">add item</a>

                    </div>
                </div>
                <!-- end main title -->

                <!-- stats -->
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="stats">
                        <span>Total Movies</span>
                        <p>{{ count }}</p>
                        <i class="icon ion-ios-stats"></i>
                    </div>
                </div>
                <!-- end stats -->

                <!-- stats -->
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="stats">
                        <span>Total Users</span>
                        <p>{{ count1 }}</p>
                        <i class="icon ion-ios-film"></i>
                    </div>
                </div>
                <!-- end stats -->

                <!-- stats -->
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="stats">
                        <span>Number of Subscription</span>
                        <p>2 573</p>
                        <i class="icon ion-ios-chatbubbles"></i>
                    </div>
                </div>
                <!-- end stats -->

                <!-- stats -->
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="stats">
                        <span>Total Amount</span>
                        <p>11,021</p>
                        <i class="icon ion-ios-star-half"></i>
                    </div>
                </div>
                <!-- end stats -->


                <div class="row">
                    <!-- main title -->
                    <div class="col-12">
                        <div class="main__title">
                            <h2>Movies list</h2>

                            {#						<span class="main__title-stat">14,452 Total</span>#}
                            {##}
                            <div class="main__title-wrap">
                                {#							<!-- filter sort -->#}
                                {#							<div class="filter" id="filter__sort">#}
                                {#								<span class="filter__item-label">Sort by:</span>#}
                                {##}
                                {#								<div class="filter__item-btn dropdown-toggle" role="navigation" id="filter-sort" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
                                {#									<input type="button" value="Date created">#}
                                {#									<span></span>#}
                                {#								</div>#}
                                {##}
                                {#								<ul class="filter__item-menu dropdown-menu scrollbar-dropdown" aria-labelledby="filter-sort">#}
                                {#									<li>Date created</li>#}
                                {#									<li>Rating</li>#}
                                {#									<li>Views</li>#}
                                {#								</ul>#}
                                {#							</div>#}
                                <!-- end filter sort -->

                                <!-- search -->
                                <form action="#" class="main__title-form">
                                    <input type="text" placeholder="Find movie / tv series..">
                                    <button type="button">
                                        <i class="icon ion-ios-search"></i>
                                    </button>
                                </form>
                                <!-- end search -->
                            </div>
                        </div>
                    </div>
                    <!-- end main title -->

                    <!-- users -->
                    <div class="col-12">
                        <div class="main__table-wrap">
                            <table class="main__table">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>TITLE</th>
                                    <th>CAST</th>
                                    <th>UPLOADER NAME</th>
                                    <th>GENERS</th>
                                    <th>LANGUAGE</th>
                                    <th>STATUS</th>
                                    {#                                    <th>STATUS</th>#}


                                </tr>
                                </thead>
                                {% for i in page.object_list %}
                                    <tbody>
                                    <tr>
                                        <td>
                                            <div class="main__table-text">{{ i.id }}</div>
                                        </td>
                                        <td>
                                            <div class="main__table-text"><a href="#">{{ i.title }}</a></div>
                                        </td>
                                        <td>
                                            <div class="main__table-text">{{ i.actor_name }}</div>
                                        </td>
                                        <td>
                                            <div class="main__table-text">{{ i.uploader_name }}</div>
                                        </td>
                                        <td>
                                            <div class="main__table-text">{{ i.geners }}</div>
                                        </td>
                                        <td>
                                            <div class="main__table-text">{{ i.language }}</div>
                                        </td>

                                        <td>
                                            {% if i.status == 0 %}
                                                <div class="main__table-text" style="color: red">Inactive</div>
                                            {% else %}
                                                <div class="main__table-text" style="color: green">Active</a>
                                                </div>
                                            {% endif %}

                                        </td>
                                        {#                                    <td>#}
                                        {#										<div class="main__table-text">{{i.status }}</div>#}
                                        {#									</td>#}
                                        {#									<td>#}
                                        {#										<div class="main__table-btns">#}
                                        {#											<a href="#modal-status" class="main__table-btn main__table-btn--banned open-modal">#}
                                        {#												<i class="icon ion-ios-lock"></i>#}
                                        {#											</a>#}
                                        {#											<a href="#" class="main__table-btn main__table-btn--view">#}
                                        {#												<i class="icon ion-ios-eye"></i>#}
                                        {#											</a>#}
                                        {#											<a href="#" class="main__table-btn main__table-btn--edit">#}
                                        {#												<i class="icon ion-ios-create"></i>#}
                                        {#											</a>#}
                                        {#											<a href="#modal-delete" class="main__table-btn main__table-btn--delete open-modal">#}
                                        {#												<i class="icon ion-ios-trash"></i>#}
                                        {#											</a>#}
                                        {#										</div>#}
                                        {#									</td>#}
                                    </tr>

                                    </tbody>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                    <!-- end users -->

                    <!-- paginator -->
                    <div class="col-12">
                        <div class="paginator-wrap">
                            <span>Page Numbers</span>


                            <ul class="paginator">
                                {% if page.has_previous %}
                                    <li class="paginator__item paginator__item--prev">
                                        <a href="{% url 'publish' %}?page={{ page.previous_page_number }}"><i
                                                class="icon ion-ios-arrow-back"></i></a>
                                    </li>
                                {% endif %}

                                <li class="paginator__item paginator__item--active"><a href="#">{{ page.number }}</a>
                                </li>
                                {% if page.has_next %}
                                    <li class="paginator__item paginator__item--next">
                                        <a href="{% url 'publish' %}?page={{ page.next_page_number }}"><i
                                                class="icon ion-ios-arrow-forward"></i></a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    <!-- end paginator -->
                </div>
            </div>
        </div>
    </main>
    <!-- end main content -->
{% endblock %}

templates/publisher1/pub_add.html
{% extends 'publisher1/pub_base.html' %}

    {% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from dmitryvolkov.me/demo/hotflix2.1/main/signup.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 22 Jun 2021 10:38:39 GMT -->
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- CSS -->
	<link rel="stylesheet" href={% static 'test/css/bootstrap-reboot.min.css' %}>
	<link rel="stylesheet" href={% static "test/css/bootstrap-grid.min.css" %}>
	<link rel="stylesheet" href={% static "test/css/owl.carousel.min.css" %}>
	<link rel="stylesheet" href={% static "test/css/jquery.mCustomScrollbar.min.css" %}>
	<link rel="stylesheet" href={% static "test/css/nouislider.min.css"  %}>
	<link rel="stylesheet" href={% static "test/css/ionicons.min.css" %}>
	<link rel="stylesheet" href={% static "test/css/magnific-popup.css" %}>
	<link rel="stylesheet" href={% static  "test/css/plyr.css" %}>
	<link rel="stylesheet" href={% static  "test/css/photoswipe.css"%}>
	<link rel="stylesheet" href={% static "test/css/default-skin.css" %}>
	<link rel="stylesheet" href={% static "test/css/main.css" %}>


	<!-- Favicons -->
	<link rel="icon" type="image/png" href="icon/favicon-32x32.png" sizes="32x32">
	<link rel="apple-touch-icon" href="icon/favicon-32x32.png">

	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="Dmitry Volkov">
	<title>movie damaka</title>
</head>

<body class="body">

{% block content %}
<main class="main">
		<div class="container-fluid">

                <!-- main title -->
                <div class="col-12">
                    <div class="main__title">
                        <h2>ADDING FORM</h2>
                        <a href="/padd" class="main__title-link">add categories</a>
                    </div>
                </div>
                <div class="row" style="padding-top: 0 !important;">
                    <div class="col-12">
                        <div class="sign__content">
                            <!-- registration form -->
                            <form  class="sign__form" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="sign__group">
                                {{ pb_form.as_p }}
                                </div>
                                <button class="sign__btn" type="submit" >publish</button>
                            </form>
                            <!-- registration form -->
                        </div>
                    </div>
                </div>



	 <!-- JS -->
	<script src={% static "test/js/jquery-3.5.1.min.js" %}></script>
	<script src={% static "test/js/bootstrap.bundle.min.js" %}></script>
	<script src={% static "test/js/owl.carousel.min.js" %}></script>
	<script src={% static  "test/js/jquery.magnific-popup.min.js"%}></script>
	<script src={% static "test/js/jquery.mousewheel.min.js" %}></script>
	<script src={% static "test/js/jquery.mCustomScrollbar.min.js" %}></script>
	<script src={% static  "test/js/wNumb.js"%}></script>
	<script src={% static  "test/js/nouislider.min.js"  %}></script>
	<script src={% static "test/js/plyr.min.js" %}></script>
	<script src={% static "test/js/photoswipe.min.js" %}></script>
	<script src={% static   "test/js/photoswipe-ui-default.min.js" %}></script>
	<script src={% static  "test/js/main.js"%}></script>
        </div></main>
{% endblock %}
</body>

<!-- Mirrored from dmitryvolkov.me/demo/hotflix2.1/main/signup.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 22 Jun 2021 10:38:39 GMT -->
</html>

templates/publisher1/pub_reg.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from dmitryvolkov.me/demo/hotflix2.1/main/signup.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 22 Jun 2021 10:38:39 GMT -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS -->
    <link rel="stylesheet" href={% static 'test/css/bootstrap-reboot.min.css' %}>
    <link rel="stylesheet" href={% static "test/css/bootstrap-grid.min.css" %}>
    <link rel="stylesheet" href={% static "test/css/owl.carousel.min.css" %}>
    <link rel="stylesheet" href={% static "test/css/jquery.mCustomScrollbar.min.css" %}>
    <link rel="stylesheet" href={% static "test/css/nouislider.min.css" %}>
    <link rel="stylesheet" href={% static "test/css/ionicons.min.css" %}>
    <link rel="stylesheet" href={% static "test/css/magnific-popup.css" %}>
    <link rel="stylesheet" href={% static  "test/css/plyr.css" %}>
    <link rel="stylesheet" href={% static  "test/css/photoswipe.css" %}>
    <link rel="stylesheet" href={% static "test/css/default-skin.css" %}>
    <link rel="stylesheet" href={% static "test/css/main.css" %}>


    <!-- Favicons -->
    <link rel="icon" type="image/png" href="icon/favicon-32x32.png" sizes="32x32">
    <link rel="apple-touch-icon" href="icon/favicon-32x32.png">

    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="Dmitry Volkov">
    <title>movie damaka</title>
</head>

<body class="body">

<div class="sign section--bg" data-bg={% static "img/section/section.jpg" %}>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="sign__content">
                    <!-- registration form -->
                    <form class="sign__form" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <h1 class="login-title">PUBLISHER REG</h1>


                        <div class="sign__group">
                            <p><label for="id_first_name">First name:</label> <input type="text" class="sign__input" name="first_name"
                                                                                     maxlength="150" id="id_first_name">
                            </p>
                            <p><label for="id_last_name">Last name:</label> <input type="text" class="sign__input" name="last_name"
                                                                                   maxlength="150" id="id_last_name">
                            </p>
                            <p><label for="id_username">Username:</label> <input type="text" class="sign__input" name="username"
                                                                                 maxlength="150" required
                                                                                 id="id_username"> <span
                                    class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
                            </p>
                            <p><label for="id_password">Password:</label> <input type="password" class="sign__input" name="password"
                                                                                 maxlength="128" required
                                                                                 id="id_password"></p>
                            <p><label for="id_email">Email address:</label> <input type="email" class="sign__input" name="email"
                                                                                   maxlength="254" id="id_email"></p>
                            <p><label for="id_mobile">Mobile:</label> <input type="text" class="sign__input" name="mobile" maxlength="20"
                                                                             required id="id_mobile"></p>
                            <p><label for="id_profile_pic">Profile pic:</label> <input type="file" class="sign__input" name="profile_pic"
                                                                                       accept="image/*"
                                                                                       id="id_profile_pic"></p>
                            <p><label for="id_certificate">Certificate:</label> <input type="file" class="sign__input" name="certificate"
                                                                                       accept="image/*"
                                                                                       id="id_certificate"></p>
                            <p><label for="id_gender">Gender:</label> <select name="gender" class="sign__input" id="id_gender">
                                <option value="Male" selected>Male</option>

                                <option value="Female">Female</option>

                            </select></p>
                        </div>

                        <div class="sign__group sign__group--checkbox">
                            <input id="remember" name="remember" type="checkbox" checked="checked">
                            <label for="remember">I agree to the <a href="privacy.html">Privacy Policy</a></label>
                        </div>

                        <button class="sign__btn" type="submit">Sign Up</button>

                        <span class="sign__delimiter">or</span>

                        <div class="sign__social">
                            <a class="fb" href="#">
                                <svg viewBox="0 0 9 17" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M5.56341 16.8197V8.65888H7.81615L8.11468 5.84663H5.56341L5.56724 4.43907C5.56724 3.70559 5.63693 3.31257 6.69042 3.31257H8.09873V0.5H5.84568C3.1394 0.5 2.18686 1.86425 2.18686 4.15848V5.84695H0.499939V8.6592H2.18686V16.8197H5.56341Z"/>
                                </svg>
                            </a>
                            <a class="tw" href="#">
                                <svg viewBox="0 0 16 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M7.55075 3.19219L7.58223 3.71122L7.05762 3.64767C5.14804 3.40404 3.47978 2.57782 2.06334 1.1902L1.37085 0.501686L1.19248 1.01013C0.814766 2.14353 1.05609 3.34048 1.843 4.14552C2.26269 4.5904 2.16826 4.65396 1.4443 4.38914C1.19248 4.3044 0.972149 4.24085 0.951164 4.27263C0.877719 4.34677 1.12953 5.31069 1.32888 5.69202C1.60168 6.22165 2.15777 6.74068 2.76631 7.04787L3.28043 7.2915L2.67188 7.30209C2.08432 7.30209 2.06334 7.31268 2.12629 7.53512C2.33613 8.22364 3.16502 8.95452 4.08833 9.2723L4.73884 9.49474L4.17227 9.8337C3.33289 10.321 2.34663 10.5964 1.36036 10.6175C0.888211 10.6281 0.5 10.6705 0.5 10.7023C0.5 10.8082 1.78005 11.4014 2.52499 11.6344C4.75983 12.3229 7.41435 12.0264 9.40787 10.8506C10.8243 10.0138 12.2408 8.35075 12.9018 6.74068C13.2585 5.88269 13.6152 4.315 13.6152 3.56293C13.6152 3.07567 13.6467 3.01212 14.2343 2.42953C14.5805 2.09056 14.9058 1.71983 14.9687 1.6139C15.0737 1.41264 15.0632 1.41264 14.5281 1.59272C13.6362 1.91049 13.5103 1.86812 13.951 1.39146C14.2762 1.0525 14.6645 0.438131 14.6645 0.258058C14.6645 0.22628 14.5071 0.279243 14.3287 0.374576C14.1398 0.480501 13.7202 0.639389 13.4054 0.734722L12.8388 0.914795L12.3247 0.565241C12.0414 0.374576 11.6427 0.162725 11.4329 0.0991699C10.8978 -0.0491255 10.0794 -0.0279404 9.59673 0.14154C8.2852 0.618204 7.45632 1.84694 7.55075 3.19219Z"/>
                                </svg>
                            </a>
                            <a class="gl" href="#">
                                <svg xmlns='http://www.w3.org/2000/svg' class='ionicon' viewBox='0 0 512 512'>
                                    <path d='M473.16 221.48l-2.26-9.59H262.46v88.22H387c-12.93 61.4-72.93 93.72-121.94 93.72-35.66 0-73.25-15-98.13-39.11a140.08 140.08 0 01-41.8-98.88c0-37.16 16.7-74.33 41-98.78s61-38.13 97.49-38.13c41.79 0 71.74 22.19 82.94 32.31l62.69-62.36C390.86 72.72 340.34 32 261.6 32c-60.75 0-119 23.27-161.58 65.71C58 139.5 36.25 199.93 36.25 256s20.58 113.48 61.3 155.6c43.51 44.92 105.13 68.4 168.58 68.4 57.73 0 112.45-22.62 151.45-63.66 38.34-40.4 58.17-96.3 58.17-154.9 0-24.67-2.48-39.32-2.59-39.96z'/>
                                </svg>
                            </a>
                        </div>

                        <span class="sign__text">Already have an account? <a href="/pub_login">Sign in!</a></span>
                    </form>
                    <!-- registration form -->
                </div>
            </div>
        </div>
    </div>
</div>

<!-- JS -->
<script src={% static "test/js/jquery-3.5.1.min.js" %}></script>
<script src={% static "test/js/bootstrap.bundle.min.js" %}></script>
<script src={% static "test/js/owl.carousel.min.js" %}></script>
<script src={% static  "test/js/jquery.magnific-popup.min.js" %}></script>
<script src={% static "test/js/jquery.mousewheel.min.js" %}></script>
<script src={% static "test/js/jquery.mCustomScrollbar.min.js" %}></script>
<script src={% static  "test/js/wNumb.js" %}></script>
<script src={% static  "test/js/nouislider.min.js" %}></script>
<script src={% static "test/js/plyr.min.js" %}></script>
<script src={% static "test/js/photoswipe.min.js" %}></script>
<script src={% static   "test/js/photoswipe-ui-default.min.js" %}></script>
<script src={% static  "test/js/main.js" %}></script>
</body>

<!-- Mirrored from dmitryvolkov.me/demo/hotflix2.1/main/signup.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 22 Jun 2021 10:38:39 GMT -->
</html>